const filteredBookmarksArray = [ 
  
  { name: 'Getting started with Tails, the encrypted, leave-no-trace operating system - TechRepublic',
    url: 'https://www.techrepublic.com/article/getting-started-with-tails-the-encrypted-leave-no-trace-operating-system/' },
  { name: 'Please stop using console.log(), it’s broken… – Hacker Noon',
    url: 'https://hackernoon.com/please-stop-using-console-log-its-broken-b5d7d396cf15' },
  { name: 'I’m an imposter. – kurtiskemple – Medium',
    url: 'https://medium.com/@kurtiskemple/im-an-imposter-832418db8a45' },
  { name: 'Machine Learning Crash Course  |  Google Developers',
    url: 'https://developers.google.com/machine-learning/crash-course/' },
  { name: 'What Type of Linux Desktop or Laptop Should You Buy?',
    url: 'https://www.makeuseof.com/tag/linux-desktop-laptop-buy/' },
  { name: 'Keep your personal data private with these privacy tips for Linux.',
    url: 'https://spreadprivacy.com/linux-privacy-tips/' },
  { name: 'Qwant vs DuckDuckGo? : privacytoolsIO',
    url: 'https://www.reddit.com/r/privacytoolsIO/comments/7dguj3/qwant_vs_duckduckgo/' },
  { name: 'Bitcoin & The Point of No Return – George Kikvadze – Medium',
    url: 'https://medium.com/@BitfuryGeorge/bitcoin-the-point-of-no-return-a214f6c919e1' },
  { name: 'Taxing Every Bitcoin Purchase Will Backfire for the IRS - CoinDesk',
    url: 'https://www.coindesk.com/taxing-every-bitcoin-purchase-will-backfire-irs/?utm_content=buffer2a750&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer' },
  { name: 'Want to learn Bootstrap 4? Here’s our free 10-part course. Happy Easter!',
    url: 'https://medium.freecodecamp.org/want-to-learn-bootstrap-4-heres-our-free-10-part-course-happy-easter-35c004dc45a4' },
  { name: 'How to Improve Your Memory: Tips and Exercises to Sharpen Your Mind and Boost Brainpower',
    url: 'http://www.helpguide.org/articles/memory/how-to-improve-your-memory.html' },
  { name: 'On quitting from a millennial perspective — with love',
    url: 'https://medium.com/@beatrizricci/on-quitting-from-a-millennial-perspective-with-love-f5e37306bba1' },
  { name: 'In the AI Age, “Being Smart” Will Mean Something Completely Different',
    url: 'https://hbr.org/2017/06/in-the-ai-age-being-smart-will-mean-something-completely-different' },
  { name: 'A New SegWit Signaling Period Has Started and All Mining Pools Are Signaling - CoinDesk',
    url: 'http://snip.ly/opnld#https://www.coindesk.com/new-segwit-signaling-period-started-mining-pools-signaling/' },
  { name: '11 Do\'s and Don\'ts of Tor Network - Hongkiat',
    url: 'https://www.google.co.uk/amp/www.hongkiat.com/blog/do-donts-tor-network/amp/' },
  { name: 'Why Do Programming Languages Have Weird Names? | Freelancer Blog',
    url: 'https://www.freelancer.com/community/articles/why-do-programming-languages-have-weird-names?utm_campaign=20170824weirdol&utm_medium=email&utm_source=readstory&ft_prog=MEE&ft_prog_id=850016505' },
  { name: 'This app is leading the revolution in free access to scientific papers - ScienceAlert',
    url: 'http://www.sciencealert.com/the-app-that-lets-you-read-scientific-papers-free-is-transforming-how-we-access-knowledge' },
  { name: 'Explain Ardor to me Like I am 5 – Gabriel Francesch – Medium',
    url: 'https://medium.com/@gabriel.francesch/explain-ardor-to-me-like-i-am-5-64a92cc63041' },
  { name: 'The environment needs cryptogovernance : Nature News & Comment',
    url: 'https://www.nature.com/news/the-environment-needs-cryptogovernance-1.22023' },
  { name: 'What can blockchain do for the environment? | Ensia',
    url: 'https://ensia.com/features/blockchain-environment-sustainability/' },
  { name: '2017: The Year Blockchain Got Weird - CoinDesk',
    url: 'https://www.coindesk.com/2017-year-blockchain-got-weird/amp/?__twitter_impression=true' },
  { name: '40 Badass Women in Emerging Tech to Follow on Twitter',
    url: 'https://code.likeagirl.io/40-badass-women-in-emerging-tech-to-follow-on-twitter-26e55ee39fa2' },
  { name: 'Developer Guide - Bitcoin',
    url: 'https://bitcoin.org/en/developer-guide' },
  { name: 'How Recursion Works — explained with flowcharts and a video',
    url: 'https://medium.freecodecamp.org/how-recursion-works-explained-with-flowcharts-and-a-video-de61f40cb7f9?gi=bf2712f531cb' },
  { name: '30 Linux System Monitoring Tools Every SysAdmin Should Know - nixCraft',
    url: 'https://www.cyberciti.biz/tips/top-linux-monitoring-tools.html/amp?__twitter_impression=true' },
  { name: 'Learn Python in 3 days : Step by Step Guide - Data Science Central',
    url: 'https://www.datasciencecentral.com/profiles/blogs/learn-python-in-3-days-step-by-step-guide' },
  { name: 'Python Tutorial from Scratch : Learn in 3 Days',
    url: 'http://www.listendata.com/2017/05/python-tutorial.html?m=1' },
  { name: 'Know the Difference Between AI, Machine Learning, and Deep Learning',
    url: 'https://edgylabs.com/know-the-difference-between-ai-machine-learning-deep-learning?utm_content=buffer822f4&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer' },
  { name: 'The Challenges of Building Ethereum Infrastructure – Jameson Lopp – Medium',
    url: 'https://medium.com/@lopp/the-challenges-of-building-ethereum-infrastructure-87e443e47a4b' },
  { name: 'The 9 Best Free Online Big Data And Data Science Courses',
    url: 'https://www.forbes.com/sites/bernardmarr/2017/06/06/the-9-best-free-online-big-data-and-data-science-courses/#31b00f6543cd' },
  { name: 'Your first robot: A beginner’s guide to ROS and Ubuntu Core [1/5] | Ubuntu Insights',
    url: 'https://insights.ubuntu.com/2017/12/19/your-first-robot-a-beginners-guide-to-ros-and-ubuntu-core-1-5/' },
  { name: 'I wish I knew these before diving into React – OpsGenie Engineering',
    url: 'https://engineering.opsgenie.com/i-wish-i-knew-these-before-diving-into-react-301e0ee2e488' },
  { name: 'You learned the basics of React, now what? – OpsGenie Engineering',
    url: 'https://engineering.opsgenie.com/you-learned-the-basics-of-react-now-what-389e69be3c5a' },
  { name: 'How I made a talking emoji using regular emojis and JavaScript | Codementor',
    url: 'https://www.codementor.io/mauriziocarboni/how-i-made-a-talking-emoji-using-regular-emojis-and-javascript-etmz7svtg?utm_swu=7100&utm_content=65396065&utm_medium=social&utm_source=twitter' },
  { name: 'How can blockchain help helpless farmers? – Hacker Noon',
    url: 'https://hackernoon.com/how-can-blockchain-help-helpless-farmers-42ba836352f2' },
  { name: 'The freeCodeCamp Podcast: Ep. 12 - Ten Rules for Negotiating a Job Offer',
    url: 'https://freecodecamp.libsyn.com/ep-12-ten-rules-for-negotiating-a-job-offer' },
  { name: 'Blockchains Never Forget',
    url: 'https://www.ribbonfarm.com/2017/05/25/blockchains-never-forget/' },
  { name: 'Meet the Mysterious Hacking Collective Who Love Trolling Anonymous - VICE',
    url: 'https://www.google.co.uk/amp/s/www.vice.com/amp/en_uk/article/nn4gvk/rustle-league-are-making-sure-trolling-stays-funny' },
  { name: 'A Formal Language for Analyzing Contracts | Satoshi Nakamoto Institute',
    url: 'http://nakamotoinstitute.org/contract-language/' },
  { name: 'This Startup Is Using Blockchain Tech To Rethink Cyber Security In The Bitcoin Era',
    url: 'https://www.forbes.com/sites/julianmitchell/2017/12/31/this-startup-uses-blockchain-tech-to-rethink-cyber-security-in-the-bitcoin-era/#2cfef0692b39' },
  { name: '2017 Was The Year When Everyone (Finally) Learned Bitcoin Isn\'t Controlled By Miners',
    url: 'https://www.forbes.com/sites/ktorpey/2017/11/30/2017-was-the-year-when-everyone-finally-learned-bitcoin-isnt-controlled-by-miners/#3c26ecdc4de3' },
  { name: '5 Python Development Setup Tips to Boost Your Productivity – dbader.org',
    url: 'https://dbader.org/blog/python-development-setup-tips-to-boost-your-productivity' },
  { name: 'Blockchains Startup Jobs - AngelList',
    url: 'https://angel.co/blockchains/jobs' },
  { name: 'Decentralization in Bitcoin and Ethereum',
    url: 'http://hackingdistributed.com/2018/01/15/decentralization-bitcoin-ethereum/' },
  { name: 'Build Super Fast Apps in Node.js using Redis Cache – manifoldco',
    url: 'https://blog.manifold.co/build-super-fast-apps-in-node-js-using-redis-cache-d3d55bbdc375' },
  { name: 'CNIT 127: Exploit Development -- Sam Bowne',
    url: 'https://samsclass.info/127/127_S18.shtml' },
  { name: 'Bitcoin Edge Workshops - Tutorials',
    url: 'https://bitcoinedge.org/tutorials' },
  { name: 'Implementing a Neural Network from Scratch in Python – An Introduction - Data Science Central',
    url: 'https://www.datasciencecentral.com/profiles/blogs/implementing-a-neural-network-from-scratch-in-python-an?utm_content=bufferbeeb0&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer' },
  { name: 'The Blog of Safia Abdalla — How do Promises work under the hood?',
    url: 'https://blog.safia.rocks/post/170154422915/how-do-promises-work-under-the-hood' },
  { name: 'Contributing to Bitcoin Core, a personal account – Bitcoin Tech Talk',
    url: 'https://bitcointechtalk.com/contributing-to-bitcoin-core-a-personal-account-35f3a594340b' },
  { name: 'Asking the Right Questions About AI – Yonatan Zunger – Medium',
    url: 'https://medium.com/@yonatanzunger/asking-the-right-questions-about-ai-7ed2d9820c48' },
  { name: 'How to Make Your Code CLEAN and BEAUTIFUL – Hacker Noon',
    url: 'https://hackernoon.com/how-to-make-your-code-clean-and-beautiful-5ff7aee03be6' },
  { name: 'An Intro to Color Theory: How to combine colors and set the mood of your designs',
    url: 'https://medium.freecodecamp.org/an-intro-to-color-theory-how-to-combine-colors-and-set-the-mood-of-your-designs-79bf5a45b3d' },
  { name: '10 Hacking Tools You Think Would be Illegal But are for Sale Online | Inverse',
    url: 'https://www.inverse.com/article/38612-hacking-tools-legal-available' },
  { name: 'The authoritative guide to blockchain development – freeCodeCamp',
    url: 'https://medium.freecodecamp.org/the-authoritative-guide-to-blockchain-development-855ab65b58bc' },
  { name: 'Cypherpunks, Bitcoin & the Myth of Satoshi Nakamoto | Cybersalon',
    url: 'http://cybersalon.org/cypherpunk/' },
  { name: 'A Declaration of the Independence of Cyberspace | Electronic Frontier Foundation',
    url: 'https://www.eff.org/cyberspace-independence' },
  { name: 'Satoshi Roundtable IV Recap – Jameson Lopp – Medium',
    url: 'https://medium.com/@lopp/satoshi-roundtable-iv-recap-d7828e9f9e5e' },
  { name: 'The Crypto Anarchist Manifesto',
    url: 'https://www.activism.net/cypherpunk/crypto-anarchy.html' },
  { name: 'Power Ledger vs WePower — Steemit',
    url: 'https://steemit.com/cryptocurrency/@surryhillsteemer/power-ledger-vs-wepower' },
  { name: 'A survey on security and privacy issues of Bitcoin – the morning paper',
    url: 'https://blog.acolyer.org/2018/02/15/a-survey-on-security-and-privacy-issues-of-bitcoin/amp/?__twitter_impression=true' },
  { name: 'How To Become A Blockchain Developer: Crash Course! - Blockgeeks',
    url: 'https://blockgeeks.com/guides/blockchain-developer/' },
  { name: 'How to Hire a Good Blockchain Developer (Ultimate Guide) - Blockgeeks',
    url: 'https://blockgeeks.com/how-to-hire-a-good-blockchain-developer/' },
  { name: 'Learn Blockchain Coding & Much More. We’ll help you get clarity.',
    url: 'https://blockgeeks.com/' },
  { name: 'Courses | B9lab Academy',
    url: 'https://academy.b9lab.com/courses' },
  { name: 'Op Ed: Why Ethereum’s Hard Fork Will Cause Problems in the Coming Year',
    url: 'https://bitcoinmagazine.com/articles/op-ed-why-ethereums-hard-fork-will-cause-problems-coming-year/' },
  { name: '10 Interview Questions Every JavaScript Developer Should Know',
    url: 'https://medium.com/javascript-scene/10-interview-questions-every-javascript-developer-should-know-6fa6bdf5ad95' },
  { name: 'Earth’s Greening and BitCoin Proof of Work. Satoshi is Smiling.',
    url: 'https://medium.com/@billtai/earths-greening-and-proof-of-work-satoshi-is-smiling-13dbf059025' },
  { name: 'Getting started with Python programming | Opensource.com',
    url: 'https://opensource.com/article/17/10/python-101?sc_cid=70160000001273HAAQ' },
  { name: 'I spent 3 months applying to jobs after a coding bootcamp. Here’s what I learned.',
    url: 'https://medium.freecodecamp.org/5-key-learnings-from-the-post-bootcamp-job-search-9a07468d2331' },
  { name: 'Learn Blockchains by Building One – Hacker Noon',
    url: 'https://hackernoon.com/learn-blockchains-by-building-one-117428612f46' },
  { name: 'AI will be the art movement of the 21st century – Quartz',
    url: 'https://qz.com/1023493/ai-will-be-the-art-movement-of-the-21st-century/amp/?__twitter_impression=true' },
  { name: '9 Promising Promise Tips',
    url: 'https://dev.to/kepta/promising-promise-tips--c8f?utm_content=68408541&utm_medium=social&utm_source=twitter' },
  { name: 'How GraphQL Replaces Redux – Mark Johnson – Medium',
    url: 'https://medium.com/@wmdmark/how-graphql-replaces-redux-3fff8289221d' },
  { name: '\'Programming Blockchain\' Will Change How You See Bitcoin - CoinDesk',
    url: 'https://www.coindesk.com/programming-blockchain-will-change-see-bitcoin/amp/?__twitter_impression=true' },
  { name: 'Lightning Network Resources',
    url: 'http://lnroute.com/' },
  { name: 'Top Five Ways I gained access to Your Corporate Wireless Network (Lo0tBo0ty KARMA edition)',
    url: 'https://medium.com/@adam.toscher/top-5-ways-i-gained-access-to-your-corporate-wireless-network-lo0tbo0ty-karma-edition-f72e7995aef2' },
  { name: 'GitHub - getify/You-Dont-Know-JS: A book series on JavaScript. @YDKJS on twitter.',
    url: 'https://github.com/getify/You-Dont-Know-JS' },
  { name: 'The Linux Journal NSA Weekend Reading List: Tails and Tor | Linux Journal',
    url: 'http://m.linuxjournal.com/content/linux-journal-nsa-weekend-reading-list-tails-and-tor' },
  { name: 'The History of Lightning: From Brainstorm to Beta',
    url: 'https://bitcoinmagazine.com/articles/history-lightning-brainstorm-beta/' },
  { name: 'Schizophrenia and subvocal speech: Why people with schizophrenia hear the voices of God, spies and supernatural entities.',
    url: 'http://www.slate.com/articles/health_and_science/medical_examiner/2016/03/schizophrenia_and_subvocal_speech_why_schizophrenics_hear_the_voices_of.html' } 
]